### ISSUE TITLE
30 KB of code added to distribution

### ISSUE THREAD

**Issue by slikts** [es-shims/Object.entries#10]
Including this module causes the size of my distribution to go up by 30 KB, and presumably most of it is dead code. It doesn't seem reasonable for a simple loop to do this.

**Comment by ljharb** [comment]
I don't see why it would be dead code. It works down to ES3, so it needs to polyfill `Function#bind`, and when shimmed onto the global object, it needs to conditionally check for property descriptor support.

When I run `browserify` locally, I do end up with a file that's 28K.

So part of the size is that there's an `Object.keys` polyfill included (`object-keys`), part is `Function#bind` (`function-bind`), part is `Array#forEach` (`for-each`).

One quick way to decrease the size if you don't target ES3 (say, if you target ES5 or above) would be to alias these three polyfills to simply `module.exports = Object.keys`, `module.exports = Function.prototype.bind`, and `module.exports = Array.prototype.forEach`. It's also likely that these modules will already dedupe with other things.

**Comment by ljharb** [comment]
(In other words, `Object.entries` is in no way a simple loop, and it needs to also be robust against someone deleting or overriding global builtins)

**Comment by slikts** [comment]
FWIW `istanbul cover` suggests that about 60% code is not executed. In any case, there should be a warning that this isn't as small as it looks to avoid surprises.

**Comment by ljharb** [comment]
@slikts sure, it contains polyfills - in a given engine, 100% of the code is never executed. The point is that across _all the engines it supports combined_, it has 100% coverage.

**Comment by ljharb** [comment]
Also, if "as it looks" doesn't include dependencies, that's an issue with your expectations - any npm package might pull in a core module, or a lot of deps, or none.
