### ISSUE TITLE
Exclude test output from npm package

### ISSUE THREAD

**Issue by insin** [es-shims/Object.entries#12]
The npm package for this module currently contains a 732 kB testling output file:

https://unpkg.com/object.entries@1.0.4/

Would it be possible to add it to `.gitignore`?

I would have submitted a PR, but can't see where the specific output filename used comes from.

**Comment by ljharb** [comment]
Sure, that seems reasonable, since it can be reproduced easily if needed with a `testling` command, and it's not required to run the tests. (it wasn't intentionally included anyways).
