### ISSUE TITLE
Question about implementation

### ISSUE THREAD

**Issue by Swizz** [es-shims/Object.entries#13]
Hi,

This is just curiosity more than other,

But, I took the habit to use this "implementation" : 
```js
Object.entries = (obj) => Object.keys(obj).map((key) => [key, obj[key]])
```
And the same one for `Object.values`
```js
Object.values = (obj) => Object.keys(obj).map((key) => obj[key])
```

I was curious about your implementation before, but thought this is was for old browser support.

But, Today, `Object.entries` is part of our browsers, and I realised, that
```js
Object.entriesMine({a: 1, b: 2, c: 3}) === Object.entriesBrowser({a: 1, b: 2, c: 3})
> false
```
Could you enlighten me about that thing ?

Thank you,

**Comment by ljharb** [comment]
I'm not sure specifically why they differ, but using a simple Object.keys + map doesn't account for changes made by getters during the access - ie, properties could be added, deleted, or made enumerable or non-enumerable.

See https://github.com/es-shims/Object.entries/blob/master/implementation.js#L11-L15 for an example of this check.

**Comment by Swizz** [comment]
I think I have understood a bit more, thank you for your time !
