### ISSUE TITLE
too complex

### ISSUE THREAD

**Issue by ancms2600** [es-shims/Object.entries#14]
why not simply
```
Object.prototype.entries || Object.defineProperty(Object.prototype, 'entries', { // shim
    enumerable: false,
    value: function() { return Object.keys(this).map(k=>[k,this[k]]); }
});
```

**Comment by ljharb** [comment]
Because then it would violate the spec. Every single line of code in the implementation is absolutely required for spec compliance.

**Comment by ljharb** [comment]
If you try it out locally, you’ll see how many tests fail.

**Comment by ljharb** [comment]
This is also a duplicate of #13.
