### ISSUE TITLE
Shim doesn't work on Chrome 49

### ISSUE THREAD

**Issue by gladiatorAsh** [es-shims/Object.entries#15]
Chrome 49 with this shim still doesn't recognize Object.entries.
![image](https://user-images.githubusercontent.com/6958341/67884305-d4c99d80-fb02-11e9-85ef-f480ccb3a8c3.png)

Have tested with portable Chromium 49.0.2623.23 on Win 10.

**Comment by ljharb** [comment]
Can you share the code you’re using?

**Comment by gladiatorAsh** [comment]
No code needed. Just installed portable Chrome 49. Loaded shim. Opened console to check for Object.entries

**Comment by ljharb** [comment]
How did you load the shim, i mean?

**Comment by ljharb** [comment]
I can’t reproduce this.
