### ISSUE TITLE
Add example for ES6 to README

### ISSUE THREAD

**Issue by C3realGuy** [es-shims/Object.entries#7]
Maybe add a small example for ES6 usage to README.md to make usage of Object.entries() more clear.

```
import entries from 'object.entries';

if (!Object.entries) {
    entries.shim();
}

var exampleObject = {foo: "bar", foo2: "bar2"};

for(let [key, value] of Object.entries(exampleObject)){
  console.log(key+" "+value);
}
```

**Comment by ljharb** [comment]
I'm not sure how `import` vs `require` makes usage of the package any different - the README already has an example of both modular and shimmed usage.

In general, examples for feature X shouldn't rely unnecessarily on feature Y - in this case, `for..of` support.

**Comment by C3realGuy** [comment]
That's a point, but still i had to dig into the code to understand how things are working, wouldn't use Object.entries without an ES6 syntax, but that's more a personal preference. I think the ES6 example is more clear how Object.entries is useful as some `assert.deepEqual(Object.entries(obj), expected);`. I never used this _assert_ module, maybe i'm missing something out. Anyways, the example relies on this assert module, which is not needed to use Object.entries and therefore not a good and self explaining example in my opinion.

If we think about the future, ES6 will be the standard, why not give it a short example?
I'm using Object.entries only for [key, value], that was the reason i looked for this module, and maybe some others are doing this too. A self explaining example would be a good thing.

**Comment by ljharb** [comment]
Sure, PRs welcome.

Fwiw, assert is both a nice core module and common pseudocode throughout CS and every language to denote assertions.

**Comment by pabrams** [comment]
How do I use the 'auto.js' functionality?  I don't want to add a bunch of code; that's what I'm trying to avoid by using a polyfill.

**Comment by ljharb** [comment]
@pabrams `import 'object.entries/auto'` or `require('object.entries/auto')` in your app's entry point is sufficient.

**Comment by ljharb** [comment]
Closing for now; happy to accept documentation PRs in the future.
